-- Благотворительный фонд — установка в Supabase
--
-- КАК ЗАПУСКАТЬ (важно):
-- 1. SQL Editor → New query
-- 2. Вставить ВЕСЬ этот файл (Ctrl+A здесь, Ctrl+C)
-- 3. В Supabase в поле редактора Ctrl+A → Ctrl+V (ничего не выделяйте частично!)
-- 4. Run (Ctrl+Enter)
-- 5. В Results должна быть таблица verify: projects = 5, categories = 5
--
-- Если раньше уже запускали и были ошибки «policy already exists»:
-- сначала выполните 00_reset_fund_tables.sql, потом снова этот файл.

-- ---------------------------------------------------------------------------
-- Функции
-- ---------------------------------------------------------------------------
create or replace function public.app_role_level(role text)
returns integer
language sql
immutable
as $$
  select case role
    when 'admin' then 3
    when 'coordinator' then 2
    when 'volunteer' then 1
    else 0
  end;
$$;

create or replace function public.current_role_level()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select public.app_role_level(
    coalesce(
      (select p.role from public.profiles p where p.id = auth.uid()),
      'volunteer'
    )
  );
$$;

-- ---------------------------------------------------------------------------
-- Таблицы
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique,
  display_name text not null,
  role text not null default 'volunteer'
    check (role in ('volunteer', 'coordinator', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  deleted_at timestamptz
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  last_name text not null,
  first_name text not null,
  country text not null,
  birth_year integer not null,
  deleted_at timestamptz
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references public.categories (id),
  deleted_at timestamptz
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  card_number text not null,
  card_issued_at timestamptz not null,
  card_expires_at timestamptz not null,
  deleted_at timestamptz
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  code text not null unique,
  year integer not null,
  goal_amount integer not null,
  category_id bigint not null references public.categories (id),
  partner_ids bigint[] not null default '{}',
  tag_ids bigint[] not null default '{}',
  volunteers_total integer not null default 0,
  volunteers_active integer not null default 0,
  deleted_at timestamptz
);

-- ---------------------------------------------------------------------------
-- Триггер профиля при регистрации
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'), ''), split_part(new.email, '@', 1)),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1)),
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'volunteer')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- RLS (политики снимаем здесь — таблицы уже созданы)
-- ---------------------------------------------------------------------------
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
drop policy if exists "profiles_update_own_display" on public.profiles;
drop policy if exists "profiles_admin_update_roles" on public.profiles;
drop policy if exists "categories_select_auth" on public.categories;
drop policy if exists "partners_select_auth" on public.partners;
drop policy if exists "tags_select_auth" on public.tags;
drop policy if exists "volunteers_select_auth" on public.volunteers;
drop policy if exists "projects_select_auth" on public.projects;
drop policy if exists "categories_write_coordinator" on public.categories;
drop policy if exists "partners_write_coordinator" on public.partners;
drop policy if exists "tags_write_coordinator" on public.tags;
drop policy if exists "volunteers_write_coordinator" on public.volunteers;
drop policy if exists "projects_write_coordinator" on public.projects;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.partners enable row level security;
alter table public.tags enable row level security;
alter table public.volunteers enable row level security;
alter table public.projects enable row level security;

create policy "profiles_select_own_or_admin"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.current_role_level() >= 3);

create policy "profiles_update_own_display"
  on public.profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "profiles_admin_update_roles"
  on public.profiles for update to authenticated
  using (public.current_role_level() >= 3)
  with check (public.current_role_level() >= 3);

create policy "categories_select_auth"
  on public.categories for select to authenticated using (true);
create policy "partners_select_auth"
  on public.partners for select to authenticated using (true);
create policy "tags_select_auth"
  on public.tags for select to authenticated using (true);
create policy "volunteers_select_auth"
  on public.volunteers for select to authenticated using (true);
create policy "projects_select_auth"
  on public.projects for select to authenticated using (true);

create policy "categories_write_coordinator"
  on public.categories for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "partners_write_coordinator"
  on public.partners for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "tags_write_coordinator"
  on public.tags for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "volunteers_write_coordinator"
  on public.volunteers for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "projects_write_coordinator"
  on public.projects for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

-- ---------------------------------------------------------------------------
-- Seed
-- ---------------------------------------------------------------------------
insert into public.categories (id, name) values
  (1, 'Дети и образование'),
  (2, 'Медицина'),
  (3, 'Экология'),
  (4, 'Социальная помощь'),
  (5, 'Культура')
on conflict (id) do nothing;

insert into public.partners (id, last_name, first_name, country, birth_year) values
  (1, 'Ромашка', 'НКО', 'Россия', 2010),
  (2, 'Медлайн', 'Фонд', 'Россия', 2005),
  (3, 'Green', 'Future', 'Германия', 2015),
  (4, 'Hope', 'International', 'США', 1998),
  (5, 'Светлый', 'Путь', 'Беларусь', 2012),
  (6, 'Культура+', 'Центр', 'Россия', 2008),
  (7, 'Еда', 'Для всех', 'Россия', 2016),
  (8, 'Регион', 'Партнёр', 'Казахстан', 2011)
on conflict (id) do nothing;

insert into public.tags (id, name, category_id) values
  (1, 'Сбор средств', 1),
  (2, 'Волонтёрство', 4),
  (3, 'Срочная помощь', 2),
  (4, 'Долгосрочная программа', 1),
  (5, 'Региональный проект', 3),
  (6, 'Культурный обмен', 5),
  (7, 'Медоборудование', 2),
  (8, 'Экоакции', 3)
on conflict (id) do nothing;

insert into public.volunteers (
  id, first_name, last_name, email, card_number, card_issued_at, card_expires_at
) values
  (1, 'Мария', 'Иванова', 'maria.ivanova@example.com', 'VL-1001', '2023-01-10', '2026-01-10'),
  (2, 'Алексей', 'Петров', 'alex.petrov@example.com', 'VL-1002', '2022-06-01', '2025-06-01'),
  (3, 'Елена', 'Сидорова', 'elena.s@example.com', 'VL-1003', '2024-03-15', '2027-03-15')
on conflict (id) do nothing;

insert into public.projects (
  id, title, code, year, goal_amount, category_id,
  partner_ids, tag_ids, volunteers_total, volunteers_active
) values
  (1, 'Школьные наборы', 'PRJ-001', 2022, 500000, 1, '{1,2}', '{1,4}', 40, 32),
  (2, 'Лечение детей', 'PRJ-002', 2023, 1200000, 2, '{1}', '{1,3}', 25, 20),
  (3, 'Чистый берег', 'PRJ-003', 2021, 300000, 3, '{3,4}', '{2,5}', 80, 55),
  (4, 'Тёплый дом', 'PRJ-004', 2024, 800000, 4, '{2,5}', '{3,4}', 30, 28),
  (5, 'Музей для всех', 'PRJ-005', 2020, 450000, 5, '{6}', '{2,4}', 15, 12)
on conflict (id) do nothing;

do $$
begin
  perform setval(pg_get_serial_sequence('public.categories', 'id'), (select coalesce(max(id), 1) from public.categories));
  perform setval(pg_get_serial_sequence('public.partners', 'id'), (select coalesce(max(id), 1) from public.partners));
  perform setval(pg_get_serial_sequence('public.tags', 'id'), (select coalesce(max(id), 1) from public.tags));
  perform setval(pg_get_serial_sequence('public.volunteers', 'id'), (select coalesce(max(id), 1) from public.volunteers));
  perform setval(pg_get_serial_sequence('public.projects', 'id'), (select coalesce(max(id), 1) from public.projects));
end $$;

-- Итог (это и смотрите в Results — не одна строка setval, а 5 строк):
select 'verify' as step, 'categories' as table_name, count(*)::bigint as rows from public.categories
union all select 'verify', 'partners', count(*) from public.partners
union all select 'verify', 'tags', count(*) from public.tags
union all select 'verify', 'volunteers', count(*) from public.volunteers
union all select 'verify', 'projects', count(*) from public.projects
order by table_name;
