-- Благотворительный фонд — схема для Supabase (SQL Editor)
-- Запуск: вставить весь файл → Run (или Ctrl+Enter)

-- ---------------------------------------------------------------------------
-- Вспомогательные функции (роли как в приложении)
-- ---------------------------------------------------------------------------

create or replace function public.app_role_level(role text)
returns integer
language sql
immutable
as $$
  select case role
    when 'admin' then 3
    when 'coordinator' then 2
    when 'volunteer' then 1
    else 0
  end;
$$;

create or replace function public.current_role_level()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select public.app_role_level(
    coalesce(
      (select p.role from public.profiles p where p.id = auth.uid()),
      ''
    )
  );
$$;

-- ---------------------------------------------------------------------------
-- Профили (связь с Supabase Auth)
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique,
  display_name text not null,
  role text not null default 'volunteer'
    check (role in ('volunteer', 'coordinator', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.current_role_level() >= 3);

create policy "profiles_update_own_display"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "profiles_admin_update_roles"
  on public.profiles for update
  to authenticated
  using (public.current_role_level() >= 3)
  with check (public.current_role_level() >= 3);

-- Новый пользователь Auth → строка в profiles (роль volunteer)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  uname text;
  dname text;
begin
  uname := coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1));
  dname := coalesce(new.raw_user_meta_data ->> 'display_name', uname);
  insert into public.profiles (id, username, display_name, role)
  values (new.id, uname, dname, 'volunteer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Справочники и сущности фонда
-- ---------------------------------------------------------------------------

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  deleted_at timestamptz
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  last_name text not null,
  first_name text not null,
  country text not null default '',
  birth_year integer not null default 2000,
  deleted_at timestamptz
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references public.categories (id),
  deleted_at timestamptz
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  card_number text not null default '',
  card_issued_at timestamptz,
  card_expires_at timestamptz,
  deleted_at timestamptz
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  code text not null unique,
  year integer not null,
  goal_amount integer not null default 0,
  category_id bigint not null references public.categories (id),
  volunteers_total integer not null default 0,
  volunteers_active integer not null default 0,
  deleted_at timestamptz
);

create table if not exists public.project_partners (
  project_id bigint not null references public.projects (id) on delete cascade,
  partner_id bigint not null references public.partners (id) on delete cascade,
  primary key (project_id, partner_id)
);

create table if not exists public.project_tags (
  project_id bigint not null references public.projects (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  primary key (project_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- RLS: чтение — все авторизованные; изменение — coordinator+
-- ---------------------------------------------------------------------------

alter table public.categories enable row level security;
alter table public.partners enable row level security;
alter table public.tags enable row level security;
alter table public.volunteers enable row level security;
alter table public.projects enable row level security;
alter table public.project_partners enable row level security;
alter table public.project_tags enable row level security;

-- SELECT (volunteer+)
create policy "categories_select" on public.categories for select to authenticated using (true);
create policy "partners_select" on public.partners for select to authenticated using (true);
create policy "tags_select" on public.tags for select to authenticated using (true);
create policy "volunteers_select" on public.volunteers for select to authenticated using (true);
create policy "projects_select" on public.projects for select to authenticated using (true);
create policy "project_partners_select" on public.project_partners for select to authenticated using (true);
create policy "project_tags_select" on public.project_tags for select to authenticated using (true);

-- INSERT/UPDATE/DELETE (coordinator+)
create policy "categories_write" on public.categories for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "partners_write" on public.partners for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "tags_write" on public.tags for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "volunteers_write" on public.volunteers for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "projects_write" on public.projects for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "project_partners_write" on public.project_partners for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

create policy "project_tags_write" on public.project_tags for all to authenticated
  using (public.current_role_level() >= 2)
  with check (public.current_role_level() >= 2);

-- ---------------------------------------------------------------------------
-- Демо-данные (как в lib/data/seed_*.dart)
-- ---------------------------------------------------------------------------

insert into public.categories (id, name) values
  (1, 'Дети и образование'),
  (2, 'Медицина'),
  (3, 'Экология'),
  (4, 'Социальная помощь'),
  (5, 'Культура')
on conflict (id) do nothing;

insert into public.partners (id, last_name, first_name, country, birth_year) values
  (1, 'Ромашка', 'НКО', 'Россия', 2010),
  (2, 'Медлайн', 'Фонд', 'Россия', 2005),
  (3, 'Green', 'Future', 'Германия', 2015),
  (4, 'Hope', 'International', 'США', 1998),
  (5, 'Светлый', 'Путь', 'Беларусь', 2012),
  (6, 'Культура+', 'Центр', 'Россия', 2008),
  (7, 'Еда', 'Банк', 'Россия', 2011)
on conflict (id) do nothing;

insert into public.tags (id, name, category_id) values
  (1, 'Сбор средств', 1),
  (2, 'Волонтёрство', 4),
  (3, 'Срочная помощь', 2),
  (4, 'Долгосрочная программа', 1),
  (5, 'Региональный проект', 3),
  (6, 'Культурный обмен', 5),
  (7, 'Медоборудование', 2),
  (8, 'Экоакции', 3)
on conflict (id) do nothing;

insert into public.volunteers (id, first_name, last_name, email, card_number, card_issued_at, card_expires_at) values
  (1, 'Мария', 'Иванова', 'maria.ivanova@example.com', 'VL-1001', '2023-01-10', '2026-01-10'),
  (2, 'Алексей', 'Петров', 'alex.petrov@example.com', 'VL-1002', '2022-06-01', '2025-06-01'),
  (3, 'Елена', 'Сидорова', 'elena.s@example.com', 'VL-1003', '2024-03-15', '2027-03-15')
on conflict (id) do nothing;

insert into public.projects (id, title, code, year, goal_amount, category_id, volunteers_total, volunteers_active) values
  (1, 'Школьные наборы', 'PRJ-001', 2022, 500000, 1, 40, 32),
  (2, 'Лечение детей', 'PRJ-002', 2023, 1200000, 2, 25, 20),
  (3, 'Чистый берег', 'PRJ-003', 2021, 300000, 3, 80, 55),
  (4, 'Тёплый дом', 'PRJ-004', 2024, 800000, 4, 30, 28),
  (5, 'Музей для всех', 'PRJ-005', 2020, 450000, 5, 15, 12)
on conflict (id) do nothing;

insert into public.project_partners (project_id, partner_id) values
  (1, 1), (1, 2),
  (2, 1),
  (3, 3), (3, 4),
  (4, 2), (4, 5),
  (5, 6)
on conflict do nothing;

insert into public.project_tags (project_id, tag_id) values
  (1, 1), (1, 4),
  (2, 1), (2, 3),
  (3, 2), (3, 5),
  (4, 3), (4, 4),
  (5, 2), (5, 4)
on conflict do nothing;

-- Синхронизация identity после явных id
select setval(pg_get_serial_sequence('public.categories', 'id'), (select coalesce(max(id), 1) from public.categories));
select setval(pg_get_serial_sequence('public.partners', 'id'), (select coalesce(max(id), 1) from public.partners));
select setval(pg_get_serial_sequence('public.tags', 'id'), (select coalesce(max(id), 1) from public.tags));
select setval(pg_get_serial_sequence('public.volunteers', 'id'), (select coalesce(max(id), 1) from public.volunteers));
select setval(pg_get_serial_sequence('public.projects', 'id'), (select coalesce(max(id), 1) from public.projects));
